instellingsdata:
  location: ""
  #dataset_combi_geaggregeerd: "data_model/Opleiding_cohort_EOI.rds"
  dataset_combi_geaggregeerd: "data_model/AS_CBS_VU_aggr.rds"
  dataset_instelling_individueel: "data_model/Export_Student_Analytics_2023-02-14_NCO_HO_hashed.rds"
  dataset_CHO_doorstroom: "data_model/Geslaagden_Cohorten_VSNU.rds"
  dataset_CHO_doorstroom_gantt: "data_model/Geslaagden_Cohorten_VSNU_geselecteerd.rds"
  driver: "SQL Server"

synthetische data:
  inherits: instellingsdata
  dataset_combi_geaggregeerd: "data_model/AS_CBS_VU_aggr_synthetisch.rds"
  dataset_instelling_individueel: "data_model/Inschrijvingen_instelling_synthetisch.rds"
  dataset_CHO_doorstroom: "data_model/Geslaagden_Cohorten_VSNU_synthetisch.rds"
  dataset_CHO_doorstroom_gantt: "data_model/Geslaagden_Cohorten_VSNU_gantt_synthetisch.rds"
  driver: "SQLServer"

default:
  inherits: instellingsdata
  location : "2.Shiny/"
